version: "2"
services:
  springDocker-app-integration:
    image: spring-app-docker-integration
#    container_name: springServer-compose
    restart: always
    build: .
    ports:
      - "9100-9999:8082"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpg
      MYSQL_HOST: mysql-server-integration
      MYSQL_PORT: 3306

  mysql_db:
     image: mysql
     container_name: mysql-server-integration
     volumes:
       - C:\Users\khalifa saidi\Desktop\db1:/var/lib/mysql
     ports:
       - "3308:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: test



