version: "2"
services:
  springDocker-app:
    image: spring-app
#    container_name: springServer-compose
    restart: always
    build: .
    ports:
      - "9100-9999:8081"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpg
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306

  mysql_db:
     image: mysql
     container_name: mysql-server
     ports:
       - "3307:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: cpg



